on:
  push:
    tags:
      - "*"

  workflow_dispatch:

name: Publish VS Code Extension — GitHub Action
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint and compile
        run: pnpm run package

      - name: Package extension
        run: pnpm exec vsce package --no-dependencies

      - name: Publish
        run: pnpm exec vsce publish --no-dependencies -p ${{ secrets.VS_MARKETPLACE_TOKEN }}
